bug fixing
spdx/tools-python pull request #180
Opened 2021-07-05 14:56 UTC by yanyag

Support writing and parsing "filesAnalyzed" into XML/JSON/YAML. 
Fix parsers to support multiple packages per document.
All the tests are passing.

2021-07-08 12:14 UTC, tardyp requested changes

2021-07-08 12:14 UTC, tardyp commented on spdx/parsers/jsonyamlxml.py
> +        if isinstance(pkg_files_analyzed, six.string_types) or isinstance(pkg_files_analyzed, bool):
according to the spec, https://spdx.github.io/spdx-spec/3-package-information/
filesAnalysed can only be a boolean.

So I would have stored the conversion to bool.

Also, we are removing six in #179 , so please don't use six for new code/

2021-07-08 12:14 UTC, tardyp commented on spdx/parsers/jsonyamlxml.py
> +        if self.document.packages[-1].files_analyzed == False:
```suggestion
        if not self.document.packages[-1].files_analyzed:
```

2021-07-08 12:14 UTC, tardyp commented on spdx/parsers/jsonyamlxml.py
> +        if self.document.packages[-1].files_analyzed == False:
why testing on packages[-1]? Sounds like a hack assuming the current package being parser is the last one.

I think we may rather want to do this test in the caller function

2021-07-08 12:14 UTC, tardyp commented on spdx/parsers/tagvalue.py
> +            self.builder.reset_package()
not sure why this change. Can you please explain?

2021-07-08 12:14 UTC, tardyp commented on spdx/writers/jsonyamlxml.py
> +        if package.files_analyzed in [True, None]:
as the default value for this field is True, we should initialize the field to True.

this test is really not obvious, and will lead to bugs in the future

2021-07-08 12:14 UTC, tardyp commented on spdx/writers/jsonyamlxml.py
> +        if package.has_optional_field("files_analyzed"):
as per spec: 3.8.3 Cardinality: Optional, one. If omitted, the default value of true is assumed.

so imho we should really initialize this to True, an only write if it is set to False

```suggestion
        if package.files_analyzed:
```

2021-07-15 19:55 UTC, tardyp commented
hi @yanyag can you please rebase this PR?

now that the six removal PR is merged, there are a few conflicts.

2021-07-27 08:27 UTC, tardyp commented
hi @yanyag  @itraviv ,

Please remember you still have this PR open that needs rebasing. It still contains merge conflicts.

Now the PR contains more fixes than initially pushed, and it becoming less trivial.
I think it will need more unit tests, with 2.2 file examples which proves that your code is actually working.

2021-07-28 15:26 UTC, pombredanne commented
Gentle ping :)

2021-07-28 18:34 UTC, itraviv commented
hi, we will probably need some time until we'll be able to have this MR ready due to capacity. will ping when ready.

2021-09-14 15:54 UTC, pombredanne commented
gentle ping :) Any update?

2022-10-20 10:31 UTC, armintaenzertng commented
As this PR is still in draft mode and has not been receiving vital updates for over a year, I suggest closing it.

@yanyag, any objections?

2022-10-31 17:18 UTC, nicoweidner commented
Closing this due to inactivity, please ping if it should be reopened.

2022-10-31 17:18 UTC, closed without merging