Refactor validation
spdx/tools-python pull request #371
Opened 2022-12-12 14:57 UTC by armintaenzertng

will fix #307

2022-12-15 12:19 UTC, meretp requested changes
Thanks for all the effort and especially dealing with the whole spec to get all validations, that must have been quite a lot! I have not dealt with the spec in such detail, but I think that you managed to implement all possible validations (except for the open issues of course), congrats on that! :1st_place_medal:   
I left quite a lot comments but most of them deal with double quotes or unused imports. I also left a comment about the architecture what we possibly should discuss. I have to admit: The more I looked into your code, the more unsure i became whether your way isn't the most suitable after all.

2022-12-15 14:54 UTC, armintaenzertng commented on tests/valid_defaults.py
> +        external_document_refs = []
You're right, good point :)

2022-12-15 15:23 UTC, armintaenzertng commented on tests/validation/test_actor_validator.py
> +def test_correct_actor_person():
ah yes, I wanted to get to that but forgot about it

2022-12-15 15:42 UTC, armintaenzertng commented on src/validation/file_validator.py
> +                    f'checksums must contain a SHA1 algorithm checksum, but is: {file.checksums}',
good point, implemented

2022-12-15 15:43 UTC, armintaenzertng commented on src/validation/actor_validator.py
> +
I believe that email addresses require more than just the @ sign. As there is no remark on this in the specification, I'll probably just leave it like this for now.

2022-12-15 15:50 UTC, armintaenzertng commented on src/validation/actor_validator.py
> +    # TODO: what is parent_id in the case of annotations?
OK

2022-12-15 15:51 UTC, armintaenzertng commented on src/validation/external_document_ref_validator.py
> +        if not re.match(r"^DocumentRef-[\da-zA-Z.+-]+$", external_document_ref.document_ref_id):
Very true

2022-12-21 10:34 UTC, armintaenzertng commented on tests/validation/test_actor_validator.py
> +    actor = Actor(ActorType.PERSON, "person name", "mail@mail.com")
The purpose of the `get_...` methods is to quickly provide valid objects at places where they are just needed but not tested. Basically replacing mock function calls. Here, though, the purpose of the test is to explicitly test the given values. I'd rather not depend on some external function for this that could be changed in another context.

2022-12-21 11:04 UTC, armintaenzertng commented on src/validation/package_validator.py
> +        external_package_ref_validator = ExternalPackageRefValidator(self.spdx_version, package.spdx_id)
I erased it here and will mainly use keywords in the context of `ValidationContext` since there the provided parameters differ each time.

2022-12-21 11:10 UTC, armintaenzertng commented on src/validation/file_validator.py
> +from src.validation.spdx_id_validation import is_valid_spdx_id, validate_spdx_id
renamed to `is_valid_spdx_id` to `is_valid_internal_spdx_id`

2022-12-21 11:23 UTC, armintaenzertng commented on src/validation/extracted_licensing_info_validator.py
> +            return []
Don't know, removed

2022-12-21 11:28 UTC, armintaenzertng commented on tests/validation/test_document_validator.py
> +# TODO: some kind of super test is needed to test that all the subvalidations are correctly called
Made a new issue for this: https://github.com/spdx/tools-python/issues/375

2022-12-21 11:29 UTC, armintaenzertng commented on src/validation/document_validator.py
> +        # TODO: is this correct here? Also, make test for it
small issue for now: https://github.com/spdx/tools-python/issues/375

2022-12-21 11:30 UTC, armintaenzertng commented on tests/validation/test_license_expression_validator.py
> +    assert validation_messages == []
#374

2022-12-21 11:43 UTC, armintaenzertng commented on tests/validation/test_annotation_validator.py
> +                           'spdx_id must only contain letters, numbers, "." and "-" and must begin with "SPDXRef-", but is: SPDXRef-some_file'),
You are right, I forgot to implement the separate `test_spdx_id_validators`. Issue is here: #376

2022-12-21 13:06 UTC, armintaenzertng commented on src/validation/validation_message.py
> +
`__repr__` is included per default in `@dataclass`. Actually, `__eq__` is, too, so I can take that out.

2022-12-22 10:13 UTC, armintaenzertng commented on src/validation/document_validator.py
> +
refactored

2022-12-22 10:13 UTC, armintaenzertng commented on src/validation/document_validator.py
> +
refactored

2022-12-22 12:13 UTC, meretp commented on tests/validation/test_actor_validator.py
> +    actor = Actor(ActorType.PERSON, "person name", "mail@mail.com")
I see, thanks for the explanation.

2022-12-23 08:07 UTC, meretp requested changes
Looks very good to me, thanks for addressing the other comments! I have only a few small remarks left. 
One remark concerning usage: To test the validation I used the following code
```
test_pack = Package(spdx_id="spdxid", name="jusst a test", download_location="I have to put this here")
validate_package(test_pack)
```
and got  an error `Missing context`. As `ValidationContext` can be instantiated without further parameter, I was wondering if we can make this parameter optional for all validation-methods. What do you think?

2022-12-28 10:30 UTC, armintaenzertng commented on src/validation/package_validator.py
> +    # TODO: make test for this
https://github.com/spdx/tools-python/issues/386

2022-12-28 10:30 UTC, armintaenzertng commented on src/validation/package_verification_code_validator.py
> +# TODO: make test for this
https://github.com/spdx/tools-python/issues/386

2022-12-28 12:26 UTC, meretp approved these changes
Looks good to me, thank you very much for addressing all comments! :+1:

2022-12-28 12:42 UTC, merged