Issue 465 fix line mismatch
spdx/tools-python pull request #481
Opened 2023-02-14 14:17 UTC by meretp

Without this fix lines that contain a whitespace and a line break were not taken into account when counting the lines. This lead to a mismatch in the line number printed within the error message and the actual falsy line.

Working on this, I saw that the tag value parser was missing two error messages. This seems to be missing from the early states of the repo and it's rather interesting that this never popped up as it could easily cause a `KeyError`.

fixes #465

2023-02-15 10:10 UTC, maxhbr commented on spdx/parsers/lexers/tagvalue.py
> +        r"\s"
not sure if my proposal is correct. Might have misunderstood perl syntax

2023-02-15 11:16 UTC, zvr requested changes

2023-02-15 11:16 UTC, zvr commented on spdx/parsers/lexers/tagvalue.py
> +        r"\s"
You want to match whitespace, but not any newlines (which are handled in `t_newline` separately).

Ignoring non-ASCII codepoints, you only care about spaces and tabs. And you need one or more.

Therefore:

    r'[ \t]+'

2023-02-15 11:48 UTC, meretp commented
I don't quite understand why the origin regex `\s+` also matches the newline so that the line count is not increased but with your proposed changes @zvr it seems to work. I also added a testcase to verify that the line numer of the lexer matches even if there is an empty line in between.

2023-02-15 11:51 UTC, zvr commented
The `\s` matches all whitespace, including new line (`\n`). Therefore, the `t_newline` is never triggered and `lineno` is not increased.

2023-02-15 11:55 UTC, meretp commented
Ah, thanks for the explanation. And as the method `t_newline` comes before `t_whitespace` this would match empty lines with only a newline but as soon as there is another whitespace before the newline, `t_whitespace` handles the input and the newline is ignored in terms of line count, I see.

2023-02-28 10:18 UTC, armintaenzertng approved these changes
looks good to me :)

2023-03-01 09:43 UTC, armintaenzertng approved these changes

2023-03-01 09:59 UTC, merged