make relationship parsing to be more efficient through precomputation
spdx/tools-python pull request #743
Opened 2023-08-02 02:48 UTC by lumjjb

Handling of `hasFiles` field results in the list of all relationships being iterated through for each package. This change moves the creation of `existing_relationships_without_comments` to the top level in `parse_all_relationships`. 

Ideally, it would be nice to use a set for more optimal look-up (but that requires Relationship to be hashable, and probably would like a bit more input on how'd you think that would be better implemented).

2023-08-11 19:17 UTC, maxhbr approved these changes
LGTM

2023-08-11 19:26 UTC, maxhbr commented
[some related tests are failing](https://github.com/spdx/tools-python/actions/runs/5734180431/job/15829439165?pr=743):

```
 =========================== short test summary info ============================
FAILED tests/spdx/parser/jsonlikedict/test_relationship_parser.py::test_parse_has_files_without_duplicating_relationships[has_files0-existing_relationships0-contains_relationships0] - AssertionError: assert 1 == 0
 +  where 1 = len([Relationship(spdx_element_id='SPDXRef-Package', relationship_type=<RelationshipType.CONTAINS: 6>, related_spdx_element_id='SPDXRef-File1', comment=None)])
 +  and   0 = len([])
============ 1 failed, 1008 passed, 3 skipped, 4 warnings in 41.66s ============
```

you should be able to run these tests locally with `pytest`.

2023-08-11 19:26 UTC, maxhbr requested changes
tests are failing

2023-08-11 20:11 UTC, maxhbr commented
I triggered the CI

2023-08-11 20:18 UTC, lumjjb commented
Thanks! sorry for the multiple pushes, not super familiar with the tooling, just fixed the lint errors (i believe)

2023-08-11 20:19 UTC, maxhbr commented
I am happy to re-trigger and to support you.

(Sadly, I am on my way to bed. Will trigger again tomorrow, if you made new pushes)

2023-08-11 20:23 UTC, maxhbr commented
you can run the linting tests locally via:
```
$ isort src tests --check
$ black src tests --check
$ flake8 src tests
```

2023-08-11 20:35 UTC, lumjjb commented
I fixed some of the ones not caused by changes as drive-bys in this PR. Can't reproduce errors with the same tooling locally for some reason :|. So 🤞

2023-08-14 15:01 UTC, lumjjb commented
looks like all green! PTAL Thanks!

2023-08-17 14:23 UTC, armintaenzertng approved these changes
looks good, thanks :)

2023-08-17 14:24 UTC, armintaenzertng commented
I noticed that this already fixes #747

2023-08-17 14:24 UTC, merged